/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Eintty.NewAcount;
import java.awt.Color;
import kinder2.Tools;

/**
 *
 * @author Amr
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new Controls.button();
        btnCreate = new Controls.button();
        jLabel2 = new javax.swing.JLabel();
        txtNewPassword = new Controls.Password(20);
        jLabel1 = new javax.swing.JLabel();
        txtnewUser = new Controls.TextBox(20);
        jLabel4 = new javax.swing.JLabel();
        Back = new Controls.button();
        button1 = new Controls.button();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/close_32.png"))); // NOI18N
        Exit.setText("اغلاق");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(10, 410, 160, 40);

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32.png"))); // NOI18N
        btnCreate.setText("اضافه");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate);
        btnCreate.setBounds(560, 410, 160, 40);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel2.setText("اضافة  اكونت جديد");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 0, 406, 51);

        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewPassword);
        txtNewPassword.setBounds(170, 230, 220, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("الباسورد الجديد");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 240, 130, 30);
        jPanel1.add(txtnewUser);
        txtnewUser.setBounds(170, 120, 220, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("اسم المستخدم");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 110, 30);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_left_32.png"))); // NOI18N
        Back.setText("رجوع");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(190, 410, 170, 40);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/user_rss_32.png"))); // NOI18N
        button1.setText("حذف الاكونت");
        jPanel1.add(button1);
        button1.setBounds(370, 410, 170, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/12.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 840, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.WHITE);
        setSize(800,530);
    }//GEN-LAST:event_formWindowOpened

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed
  private void clear(){
     Tools.ClearText(this);
     
  
  }
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
     
      
 
      NewAcount n = new NewAcount();
       
       n.setUserName(txtnewUser.getText());
       n.setPassword(txtNewPassword.getText());
       n.Add();
       clear();
       Tools.MsgBox("Sucss");
      
       
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
           Tools.OpenForm(new login());    }//GEN-LAST:event_button3ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
      Tools.OpenForm(new frmmain());
      dispose();
      doLayout();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.button Back;
    private Controls.button Exit;
    private Controls.button btnCreate;
    private Controls.button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtnewUser;
    // End of variables declaration//GEN-END:variables
}
