/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Eintty.Teacher;
import java.awt.Color;
import kinder2.Tools;

/**
 *
 * @author Amr
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdd = new Controls.button();
        btnUpdate = new Controls.button();
        btnDelete = new Controls.button();
        btnBack = new Controls.button();
        txtPhone = new Controls.TextBox(20);
        txtPayments = new Controls.TextBox(20);
        txtName = new Controls.TextBox(20);
        txtAddres = new Controls.TextBox(20);
        txtId = new Controls.TextBox(20);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnClear = new Controls.button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAll = new Controls.button();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("المدرسين");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 0, 314, 73);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32.png"))); // NOI18N
        btnAdd.setText("اضافه");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(450, 120, 180, 50);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_down_32.png"))); // NOI18N
        btnUpdate.setText("تعديل");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(450, 190, 180, 50);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/close_32.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(450, 260, 180, 50);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_left_32.png"))); // NOI18N
        btnBack.setText("رجوع");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 660, 180, 50);

        txtPhone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone);
        txtPhone.setBounds(130, 360, 280, 40);

        txtPayments.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtPayments);
        txtPayments.setBounds(130, 300, 280, 40);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(130, 180, 280, 40);

        txtAddres.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtAddres);
        txtAddres.setBounds(130, 240, 280, 40);

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(130, 120, 280, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("الموبيل");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 370, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("المرتب");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 300, 120, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("الاسم");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 120, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("العنوان");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("رقم المدرس");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-3, 130, 103, 20);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/web_layout_32.png"))); // NOI18N
        btnClear.setText("تنظيف");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(450, 330, 180, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم المدرس", "الاسم", "العنوان", "المرتب", "phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setEditingColumn(-4);
        jTable1.setEditingRow(-4);
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(30);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 230, 740, 470);

        btnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/home_32.png"))); // NOI18N
        btnAll.setText("تجديد");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll);
        btnAll.setBounds(450, 400, 180, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 300, 1500, 470);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/6.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1390, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   Teacher t = new Teacher();
   private void SetClear(){
       Tools.ClearText(this);
       txtId.setText(t.getAutoNumber());
      
       t.getAllRow(jTable1);
       
   
   
   }
    private void SetValues(){     
       

      t.setIdTeacher(Integer.parseInt(txtId.getText()));
      t.setName(txtName.getText());
      t.setAddres(txtAddres.getText());
      t.setPayments(Double.parseDouble(txtPayments.getText()));
      t.setPhone(txtPhone.getText()); 
      txtId.setText(t.getAutoNumber());
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
       setSize(1400,760);
          setLocation(100, 50);
         
          getContentPane().setBackground(new Color(0,220,220));
         SetClear();
          t.getAllRow(jTable1);
           
    }//GEN-LAST:event_formWindowOpened

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        SetValues();
        t.Delete();
        SetClear();
        t.getAllRow(jTable1);
       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SetValues();
        
        t.Add();
        SetClear();
        t.getAllRow(jTable1);
         txtId.setText(t.getAutoNumber());
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       
        SetClear();
       txtId.setText(t.getAutoNumber());
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
     
        t.getAllRow(jTable1);
    }//GEN-LAST:event_btnAllActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int Row = jTable1.getSelectedRow();
        txtId.setText(jTable1.getValueAt(Row, 0).toString());
        txtName.setText(jTable1.getValueAt(Row, 1).toString());
        txtAddres.setText(jTable1.getValueAt(Row, 2).toString());
        txtPayments.setText(jTable1.getValueAt(Row, 3).toString());
        txtPhone.setText(jTable1.getValueAt(Row, 4).toString());
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     SetValues();
     t.Update();
      SetClear();
      txtId.setText(t.getAutoNumber());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        t.getAutoNumber();
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Tools.OpenForm(new frmmain());
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.button btnAdd;
    private Controls.button btnAll;
    private Controls.button btnBack;
    private Controls.button btnClear;
    private Controls.button btnDelete;
    private Controls.button btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddres;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPayments;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
