/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Eintty.Child;
import Eintty.ClassRoom;
import Eintty.Phon;

import java.awt.Color;

import java.text.SimpleDateFormat;
import java.util.Date;



import kinder2.Tools;


/**
 *
 * @author Amr
 */
public class frmAddChild extends javax.swing.JFrame {

    /**
     * Creates new form frmAddChild
     */
    public frmAddChild() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrId = new javax.swing.JRadioButton();
        jrName = new javax.swing.JRadioButton();
        jrAddress = new javax.swing.JRadioButton();
        jrClassName = new javax.swing.JRadioButton();
        button1 = new Controls.button();
        txtSearch = new Controls.TextBox(20);
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableAdd = new javax.swing.JTable();
        jrBirthDate = new javax.swing.JRadioButton();
        jrHiring = new javax.swing.JRadioButton();
        btnAdd = new Controls.button();
        btnUpdate = new Controls.button();
        btnDelete = new Controls.button();
        btnClear = new Controls.button();
        btnFind = new Controls.button();
        btnAll = new Controls.button();
        jrFomale = new javax.swing.JRadioButton();
        jrMale = new javax.swing.JRadioButton();
        btnBack1 = new Controls.button();
        txtDad = new Controls.TextBox(20);
        txtName = new Controls.TextBox(20);
        txtId = new Controls.TextBox(20);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new Controls.TextBox(20);
        jLabel11 = new javax.swing.JLabel();
        combobox1 = new Controls.ComboB();
        jDateBirth = new com.toedter.calendar.JDateChooser();
        jDateHiring = new com.toedter.calendar.JDateChooser();
        txtPay = new Controls.TextBox(20);
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtMother = new Controls.TextBox(20);
        jLabel12 = new javax.swing.JLabel();
        txtOther = new Controls.TextBox(20);
        jLabel13 = new javax.swing.JLabel();
        btnRemove = new Controls.button();
        btnUpdatep = new Controls.button();
        btnAddp = new Controls.button();
        button2 = new Controls.button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("اضافه طفل");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 10, 250, 70);

        jrId.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(jrId);
        jrId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrId.setText("رقم الطفل");
        getContentPane().add(jrId);
        jrId.setBounds(1140, 90, 100, 25);

        jrName.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(jrName);
        jrName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrName.setText("الاسم");
        getContentPane().add(jrName);
        jrName.setBounds(1270, 90, 90, 25);

        jrAddress.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(jrAddress);
        jrAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrAddress.setText("العنوان");
        getContentPane().add(jrAddress);
        jrAddress.setBounds(1410, 90, 100, 25);

        jrClassName.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(jrClassName);
        jrClassName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrClassName.setText("اسم الفصل");
        getContentPane().add(jrClassName);
        jrClassName.setBounds(1410, 130, 120, 25);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/search_32.png"))); // NOI18N
        button1.setText("بحث");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(1390, 170, 140, 41);

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtSearch);
        txtSearch.setBounds(1150, 170, 216, 40);

        jtableAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtableAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الطفل", "الاسم", "العنوان", "المدفوعات", "تاريخ التسجيل", "تاريخ الميلاد", "ذكر , انثى", "اسم الفصل", "رقم الفصل"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableAdd.setAlignmentX(0.8F);
        jtableAdd.setAlignmentY(0.8F);
        jtableAdd.setFillsViewportHeight(true);
        jtableAdd.setGridColor(new java.awt.Color(0, 0, 0));
        jtableAdd.setRowHeight(30);
        jtableAdd.getTableHeader().setResizingAllowed(false);
        jtableAdd.getTableHeader().setReorderingAllowed(false);
        jtableAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableAddMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableAdd);
        if (jtableAdd.getColumnModel().getColumnCount() > 0) {
            jtableAdd.getColumnModel().getColumn(0).setMinWidth(100);
            jtableAdd.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtableAdd.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 220, 990, 400);

        jrBirthDate.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(jrBirthDate);
        jrBirthDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrBirthDate.setText("تاريخ الميلاد");
        getContentPane().add(jrBirthDate);
        jrBirthDate.setBounds(1270, 130, 110, 25);

        jrHiring.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(jrHiring);
        jrHiring.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrHiring.setText("تاريخ التسجيل");
        getContentPane().add(jrHiring);
        jrHiring.setBounds(1140, 130, 120, 25);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32_1.png"))); // NOI18N
        btnAdd.setText("اضافه");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(410, 140, 140, 38);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/save_upload_32.png"))); // NOI18N
        btnUpdate.setText("تعديل");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(410, 190, 140, 38);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/close_32.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(410, 240, 140, 38);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/web_layout_32.png"))); // NOI18N
        btnClear.setText("تنظيف ");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(410, 290, 140, 38);

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/search_32.png"))); // NOI18N
        btnFind.setText("ايجاد");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind);
        btnFind.setBounds(410, 340, 140, 38);

        btnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/home_32.png"))); // NOI18N
        btnAll.setText("تحديث البيانات");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll);
        btnAll.setBounds(410, 390, 140, 38);

        jrFomale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrFomale);
        jrFomale.setText("انثى");
        jrFomale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFomaleActionPerformed(evt);
            }
        });
        getContentPane().add(jrFomale);
        jrFomale.setBounds(280, 430, 53, 25);

        jrMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrMale);
        jrMale.setText("ذكر");
        jrMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jrMale);
        jrMale.setBounds(180, 430, 45, 25);

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_left_32_1.png"))); // NOI18N
        btnBack1.setText("رجوع");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1);
        btnBack1.setBounds(20, 738, 170, 50);

        txtDad.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtDad);
        txtDad.setBounds(150, 540, 216, 34);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(150, 140, 216, 34);

        txtId.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(150, 80, 216, 34);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel3.setText("رقم الطفل");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 90, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setText("الاسم ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 90, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel5.setText("العنوان");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 200, 90, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel6.setText("يوم التسجيل");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 320, 110, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel7.setText("تاريخ الميلاد");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 380, 100, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel8.setText("ذكر , انثى ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 430, 80, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel9.setText("رقم الاب");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 540, 100, 30);

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtAddress);
        txtAddress.setBounds(150, 200, 216, 34);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel11.setText("اسم الفصل");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 480, 110, 30);
        getContentPane().add(combobox1);
        combobox1.setBounds(150, 480, 220, 30);
        getContentPane().add(jDateBirth);
        jDateBirth.setBounds(150, 380, 210, 30);
        getContentPane().add(jDateHiring);
        jDateHiring.setBounds(150, 320, 210, 30);

        txtPay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtPay);
        txtPay.setBounds(150, 260, 216, 34);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel10.setText("المدفوعات");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 260, 100, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الطفل", "رقم الاب", "رقم الام", "ارقام اخرى"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setRowHeight(30);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(560, 620, 990, 170);

        txtMother.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtMother);
        txtMother.setBounds(150, 590, 216, 34);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel12.setText("رقم الام");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 590, 110, 30);

        txtOther.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(txtOther);
        txtOther.setBounds(150, 640, 216, 34);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel13.setText("ارقام اخرى");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 640, 130, 30);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/am.png"))); // NOI18N
        btnRemove.setText("حذف");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(410, 630, 140, 40);

        btnUpdatep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/am.png"))); // NOI18N
        btnUpdatep.setText("تحديث");
        btnUpdatep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatepActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatep);
        btnUpdatep.setBounds(410, 560, 140, 40);

        btnAddp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/am.png"))); // NOI18N
        btnAddp.setText("اضافه");
        btnAddp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddpActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddp);
        btnAddp.setBounds(410, 500, 140, 40);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/address_book_warning_32.png"))); // NOI18N
        button2.setText("حالة الطفل");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(410, 440, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/4.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1570, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          setSize(1580,830);
        getContentPane().setBackground(new Color(120,225,225));
        setLocation(40,10);
             
         db.go.FillCombo("ClassRoom", "ClassName", combobox1);
         Clear();
      c.getAllRow(jtableAdd);
      p.getAllRow(jTable1);
   
    }//GEN-LAST:event_formWindowOpened
     Child c = new Child();
    private void Clear(){
      Tools.ClearText(this);
      txtId.setText(c.getAutoNumber());
      btnAdd.setEnabled(true);
      btnDelete.setEnabled(false);
      btnUpdate.setEnabled(false);
      txtName.requestFocus();
      
   
   }
    Phon p = new Phon();
    
    private void setValues(){
     c.setIdChild(Integer.parseInt(txtId.getText()));
     c.setChildName(txtName.getText());
     c.setAddres(txtAddress.getText());
     c.setPayments(Double.parseDouble(txtPay.getText()));
     SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
     String dateH = String.valueOf(f.format(jDateHiring.getDate()));
     String dateB = String.valueOf(f.format(jDateBirth.getDate()));
        
     c.setHiringDate(dateH);
     c.setBirthDate(dateB);
     c.setKind(ginder);
     String cName = combobox1.getSelectedItem().toString();
     String cNum = cr.getVauleByName(cName);
     c.setClassName(cName);
     c.setClassNum(Integer.parseInt(cNum));
     
       
  
    
    }
    ClassRoom cr =new ClassRoom();
   
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      setValues();
      setPhone();
      c.Add();
      p.Add();
      Clear();
      c.getAllRow(jtableAdd);
      p.getAllRow(jTable1);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String input = (String)Tools.InputBox("Input Id Child");
        int IdNumber=Integer.parseInt(input);
        c.setIdChild(IdNumber);
        c.getOneRow(jtableAdd);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
        setValues();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     
     p.setIdchild(Integer.parseInt(txtId.getText()));
     
     p.Delete();
     setValues();
     c.Delete();
     Clear();
     c.getAllRow(jtableAdd);
     p.getAllRow(jTable1);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     
     
     setValues();
       
       c.Update();
      
       Clear();
       c.getAllRow(jtableAdd);
       p.getAllRow(jTable1);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
       
        c.getAllRow(jtableAdd);
        p.getAllRow(jTable1);
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        Tools.OpenForm(new frmmain());
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jrMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMaleActionPerformed
           ginder = "Male";   
       
    }//GEN-LAST:event_jrMaleActionPerformed

    private void jrFomaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFomaleActionPerformed
        ginder = "Fomale";
    }//GEN-LAST:event_jrFomaleActionPerformed
     
    private void jtableAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableAddMouseClicked
          try {
         int row = jtableAdd.getSelectedRow();
   
             txtId.setText(jtableAdd.getValueAt(row, 0).toString());
             txtName.setText(jtableAdd.getValueAt(row, 1).toString());
             txtAddress.setText(jtableAdd.getValueAt(row, 2).toString());
             txtPay.setText(jtableAdd.getValueAt(row, 3).toString());
             
         
             SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
             Date H = df.parse(jtableAdd.getValueAt(row, 4).toString());
             Date B = df.parse(jtableAdd.getValueAt(row, 5).toString());
             jDateHiring.setDate(H);
             jDateBirth.setDate(B);
             combobox1.setSelectedItem(jtableAdd.getValueAt(row, 7));
          
    
            
      
             btnAdd.setEnabled(false);
             btnUpdate.setEnabled(true);
             btnDelete.setEnabled(true);
             
      
        } catch (Exception ex) {
             Tools.MsgBox(ex.getMessage());
        }
           
       
         
         
         
         
         
    }//GEN-LAST:event_jtableAddMouseClicked
    private String  like(){
      return "like'%" + txtSearch.getText()+"%'";
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       try{
        String search = "select * from child_data where ";
        if(jrId.isSelected()){
          search += " id like'%" + txtSearch.getText()+"%'";
        }
       else if (jrName.isSelected()){
          search += " child_name like'%" + txtSearch.getText()+"%'"; 
        } else if(jrAddress.isSelected()){
           search += " addres like '%" + txtSearch.getText()+"%'";
        }
       else if (jrBirthDate.isSelected()){
            search += " Birthdate like'%" + txtSearch.getText()+"%'";
        }
       else if(jrHiring.isSelected()){
           search += " Hiringdate like'%" + txtSearch.getText()+ "%'";
        }
       else{
             search += " Name_class like'%" + txtSearch.getText()+ "%'";
       }
     
        c.getCoustemRow(search, jtableAdd);
       }catch(Exception ex ){
          Tools.MsgBox(ex.getMessage());
       }
    }//GEN-LAST:event_button1ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
       
        setPhone();
        p.Delete();
        p.getAllRow(jTable1);
      
    }//GEN-LAST:event_btnRemoveActionPerformed
          private void  setPhone(){
             p.setIdchild(Integer.parseInt(txtId.getText()));
             p.setPhonDad(txtDad.getText());
             p.setPhonMother(txtMother.getText());
             p.setPhonOther(txtOther.getText());
             Clear();
             
          }
    private void btnUpdatepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatepActionPerformed
      
       
        setPhone();
        p.Update();
        Clear();
        p.getAllRow(jTable1);
        
    }//GEN-LAST:event_btnUpdatepActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int row1 = jTable1.getSelectedRow();
      txtId.setText(jTable1.getValueAt(row1, 0).toString());
       txtDad.setText(jTable1.getValueAt(row1, 1).toString());
       txtMother.setText(jTable1.getValueAt(row1, 2).toString());
       txtOther.setText(jTable1.getValueAt(row1, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAddpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddpActionPerformed
        setPhone();
        p.Add();
        Clear();
        p.getAllRow(jTable1);
    }//GEN-LAST:event_btnAddpActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Tools.OpenForm(new frmInf());
        dispose();
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddChild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.button btnAdd;
    private Controls.button btnAddp;
    private Controls.button btnAll;
    private Controls.button btnBack1;
    private Controls.button btnClear;
    private Controls.button btnDelete;
    private Controls.button btnFind;
    private Controls.button btnRemove;
    private Controls.button btnUpdate;
    private Controls.button btnUpdatep;
    private Controls.button button1;
    private Controls.button button2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private Controls.ComboB combobox1;
    private com.toedter.calendar.JDateChooser jDateBirth;
    private com.toedter.calendar.JDateChooser jDateHiring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrAddress;
    private javax.swing.JRadioButton jrBirthDate;
    private javax.swing.JRadioButton jrClassName;
    private javax.swing.JRadioButton jrFomale;
    private javax.swing.JRadioButton jrHiring;
    private javax.swing.JRadioButton jrId;
    private javax.swing.JRadioButton jrMale;
    private javax.swing.JRadioButton jrName;
    private javax.swing.JTable jtableAdd;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
  private String ginder;
 
}
