/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Eintty.Information;
import java.awt.Color;
import java.awt.Graphics;
import kinder2.Tools;
;

/**
 *
 * @author Amr
 */
public class frmInf extends javax.swing.JFrame {

    /**
     * Creates new form frmInf
     */
    public frmInf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNum = new Controls.TextBox(20);
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStatus = new Controls.TextTree(20);
        jScrollPane3 = new javax.swing.JScrollPane();
        txtillness = new Controls.TextTree(20);
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLevel = new Controls.TextTree(20);
        txtName = new Controls.TextBox(20);
        btnBack = new Controls.button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnUpdate = new Controls.button();
        btnAdd = new Controls.button();
        btnDelete = new Controls.button();
        btnClear = new Controls.button();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("يعانى من اى مرض\"");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(980, 270, 249, 43);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel2.setText("معلومات عن الطفل");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 0, 500, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText("اسم الطفل");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 128, 74);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setText("مستوى الطفل");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 280, 140, 21);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setText("حالة الطفل");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 260, 120, 50);

        txtNum.setEditable(false);
        txtNum.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });
        getContentPane().add(txtNum);
        txtNum.setBounds(150, 120, 230, 32);

        txtStatus.setColumns(20);
        txtStatus.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txtStatus.setRows(5);
        jScrollPane2.setViewportView(txtStatus);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(456, 330, 450, 157);

        txtillness.setColumns(20);
        txtillness.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txtillness.setRows(5);
        jScrollPane3.setViewportView(txtillness);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(946, 330, 460, 157);

        txtLevel.setColumns(20);
        txtLevel.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txtLevel.setRows(5);
        jScrollPane4.setViewportView(txtLevel);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 330, 430, 157);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(150, 190, 230, 32);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_left_32.png"))); // NOI18N
        btnBack.setText("رجوع");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 730, 160, 40);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الرقم", "الاسم", "المستوى", "الحاله", "يعانى من مرض"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(204, 255, 255));
        jTable1.setRowHeight(100);
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(300);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(300);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 490, 1410, 230);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setText("الرقم");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 110, 91, 40);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_down_32.png"))); // NOI18N
        btnUpdate.setText("تعديل");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(800, 730, 160, 40);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32_1.png"))); // NOI18N
        btnAdd.setText("اضافه");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(1000, 730, 160, 40);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/close_32.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(610, 730, 160, 40);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/web_layout_32.png"))); // NOI18N
        btnClear.setText("تنظيف");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(420, 730, 160, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/6.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1420, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setSize(1430,830);
        getContentPane().setBackground(new Color(120,225,225));
         setLocation(100,50);
         Clear();
         txtNum.setText(n.getAutoNumber());
         n.getAllRow(jTable1);
     
    }//GEN-LAST:event_formWindowOpened

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        Tools.OpenForm(new frmAddChild());
        dispose();

    }//GEN-LAST:event_btnBackActionPerformed
    Information n = new Information();
    
    private void SetValues(){
        
     n.setNumber(Integer.parseInt(txtNum.getText()));
     n.setName(txtName.getText());
     n.setLevel(txtLevel.getText());
     n.setStatus(txtStatus.getText());
     n.setIllness(txtillness.getText());
       
   
   
   }
    private void Clear(){
      Tools.ClearText(this);
      txtNum.setText(n.getAutoNumber());
      btnAdd.setEnabled(true);
      btnUpdate.setEnabled(false);
      btnDelete.setEnabled(false);
    
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SetValues();
        n.Add();
        n.getAllRow(jTable1);
        Clear();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       SetValues();
       n.Update();
       n.getAllRow(jTable1);
       Clear();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        SetValues();
        n.Delete();
        n.getAllRow(jTable1);
        Clear();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     SetValues();
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       try{
        int row =jTable1.getSelectedRow();
        txtNum.setText(jTable1.getValueAt(row, 0).toString());
        txtName.setText(jTable1.getValueAt(row, 1).toString());
        txtLevel.setText(jTable1.getValueAt(row, 2).toString());
        txtStatus.setText(jTable1.getValueAt(row, 3).toString());
        txtillness.setText(jTable1.getValueAt(row, 4).toString());
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
       }catch(Exception ex ){
          Tools.MsgBox(ex.getMessage());
       }

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.button btnAdd;
    private Controls.button btnBack;
    private Controls.button btnClear;
    private Controls.button btnDelete;
    private Controls.button btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextArea txtStatus;
    private javax.swing.JTextArea txtillness;
    // End of variables declaration//GEN-END:variables
}
