/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import kinder2.Tools;

/**
 *
 * @author Amr
 */
public class frmmain extends javax.swing.JFrame {

    
    public frmmain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new Controls.button();
        btnAddChild = new Controls.button();
        btnAbChild = new Controls.button();
        btnAbTeacher = new Controls.button();
        btnClass = new Controls.button();
        btnTeacher = new Controls.button();
        btnAboutCh = new Controls.button();
        btnCreate = new Controls.button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 60)); // NOI18N
        jLabel1.setText("الشاشه الرئيسيه");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 510, 80);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/close_32_1.png"))); // NOI18N
        btnBack.setText("خروج من البرنامج");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 670, 170, 50);

        btnAddChild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32.png"))); // NOI18N
        btnAddChild.setText("تسجيل طفل جديد");
        btnAddChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChildActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddChild);
        btnAddChild.setBounds(710, 220, 320, 70);

        btnAbChild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/address_book_32.png"))); // NOI18N
        btnAbChild.setText("غياب  الاطفال");
        btnAbChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbChildActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbChild);
        btnAbChild.setBounds(90, 330, 320, 70);

        btnAbTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/address_book_32_1.png"))); // NOI18N
        btnAbTeacher.setText("غياب المدرسين");
        btnAbTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbTeacher);
        btnAbTeacher.setBounds(90, 440, 320, 70);

        btnClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32_1.png"))); // NOI18N
        btnClass.setText("اضافت فصل جديد");
        btnClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassActionPerformed(evt);
            }
        });
        getContentPane().add(btnClass);
        btnClass.setBounds(710, 320, 320, 70);

        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/user_rss_32.png"))); // NOI18N
        btnTeacher.setText("تسجيل مدرس");
        btnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeacher);
        btnTeacher.setBounds(710, 420, 320, 70);

        btnAboutCh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/search_32.png"))); // NOI18N
        btnAboutCh.setText("كل الاطفال");
        btnAboutCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutChActionPerformed(evt);
            }
        });
        getContentPane().add(btnAboutCh);
        btnAboutCh.setBounds(400, 550, 320, 70);

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32.png"))); // NOI18N
        btnCreate.setText("اضافة اكونت جديد");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(90, 220, 320, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/7.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1160, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setSize(1120,780);
        setLocation(150,40);
        java.util.Calendar.getInstance().getTime();
    }//GEN-LAST:event_formWindowOpened

    private void btnAddChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChildActionPerformed
        Tools.OpenForm(new frmAddChild());
        dispose();
    }//GEN-LAST:event_btnAddChildActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
     
      Tools.OpenForm(new CreateAccount());
        dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassActionPerformed
       Tools.OpenForm(new frmClassRoom());
        dispose();
    }//GEN-LAST:event_btnClassActionPerformed

    private void btnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherActionPerformed
        Tools.OpenForm(new Employee());
        dispose();
    }//GEN-LAST:event_btnTeacherActionPerformed

    private void btnAboutChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutChActionPerformed
         Tools.OpenForm(new AboutChild());
        dispose();   
    }//GEN-LAST:event_btnAboutChActionPerformed

    private void btnAbChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbChildActionPerformed
        Tools.OpenForm(new frmAbsence());
        dispose();
    }//GEN-LAST:event_btnAbChildActionPerformed

    private void btnAbTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbTeacherActionPerformed
       Tools.OpenForm(new presenceOrAbsence());
        dispose();
    }//GEN-LAST:event_btnAbTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.button btnAbChild;
    private Controls.button btnAbTeacher;
    private Controls.button btnAboutCh;
    private Controls.button btnAddChild;
    private Controls.button btnBack;
    private Controls.button btnClass;
    private Controls.button btnCreate;
    private Controls.button btnTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
