/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Eintty.Absence;
import Eintty.Child;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;





import kinder2.Tools;

/**
 *
 * @author Amr
 */
public class presenceOrAbsence extends javax.swing.JFrame {

    /**
     * Creates new form presenceOrAbsence
     */
    public presenceOrAbsence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSuper = new Controls.TextBox(20);
        txtName = new Controls.TextBox(20);
        txtNumber = new Controls.TextBox(20);
        jLabel2 = new javax.swing.JLabel();
        btnBack = new Controls.button();
        btnAdd = new Controls.button();
        btnClear = new Controls.button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDay = new Controls.TextBox(20);
        txtJop = new Controls.TextBox(20);
        btnDelete = new Controls.button();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("غياب المدرسين");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 0, 720, 80);

        txtSuper.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtSuper);
        txtSuper.setBounds(150, 310, 235, 40);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(151, 188, 235, 40);

        txtNumber.setEditable(false);
        txtNumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtNumber);
        txtNumber.setBounds(151, 127, 235, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("اسم الفصل المهتم به");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 310, 150, 33);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/arrow_left_32.png"))); // NOI18N
        btnBack.setText("رجوع");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 536, 160, 50);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/add_32.png"))); // NOI18N
        btnAdd.setText("اضافه");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(400, 160, 150, 50);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/web_layout_32.png"))); // NOI18N
        btnClear.setText("تنظيف");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(400, 310, 150, 50);

        jTable.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الرقم", "اسم المدرس", "الوظيفه الموكله", "الفصل المهتم به", "سبب الغياب", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setCellSelectionEnabled(true);
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable.setEditingColumn(70);
        jTable.setEditingRow(-4);
        jTable.setFillsViewportHeight(true);
        jTable.setGridColor(new java.awt.Color(255, 255, 255));
        jTable.setRowHeight(30);
        jTable.setRowMargin(5);
        jTable.getTableHeader().setResizingAllowed(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTableComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMinWidth(100);
            jTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 140, 670, 450);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("الوظيفه");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 250, 99, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("الاسم");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 140, 33);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("الرقم");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 99, 33);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("التاريخ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 430, 99, 33);

        txtDay.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtDay);
        txtDay.setBounds(150, 370, 235, 40);

        txtJop.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(txtJop);
        txtJop.setBounds(150, 250, 235, 40);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/close_32.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(400, 240, 150, 50);
        getContentPane().add(jDateChooser);
        jDateChooser.setBounds(150, 430, 240, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("السبب");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 370, 99, 33);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/5.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1240, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
   
  
     
 

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked
   Child c = new  Child();
    private void s (){
   
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocation(60,40);
        setSize(1250,640);
        getContentPane().setBackground(new Color(120,225,225));
        txtNumber.setText(a.getAutoNumber());
        a.getAllRow(jTable);
    }//GEN-LAST:event_formWindowOpened
     Absence a = new Absence();
     private void Clear(){
        Tools.ClearText(this);
        txtNumber.setText(a.getAutoNumber());
        txtName.requestFocus();
     
     }
    private void SetValues(){
       
    a.setIdTeach(Integer.parseInt(txtNumber.getText()));
    a.setNameTeach(txtName.getText());
    a.setJobTeach(txtJop.getText());
    a.setSuberTeach(txtSuper.getText());
    a.setDayTeach(txtDay.getText());
    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
    String H = String.valueOf(f.format(jDateChooser.getDate()));
    a.setHiring(H);
    
    
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       Tools.OpenForm(new frmmain());
       dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jTableComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTableComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableComponentHidden

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    SetValues();
    a.Add();
    Clear();
    a.getAllRow(jTable);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       SetValues();
       a.Delete();
       a.getAllRow(jTable);
       Clear();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
       try{
        int Row = jTable.getSelectedRow();
        txtNumber.setText(jTable.getValueAt(Row, 0).toString());
        txtName.setText(jTable.getValueAt(Row, 1).toString());
        txtJop.setText(jTable.getValueAt(Row, 2).toString());
        txtSuper.setText(jTable.getValueAt(Row, 3).toString());
        txtDay.setText(jTable.getValueAt(Row, 4).toString());
           SimpleDateFormat df =new SimpleDateFormat("yyyy-MM-dd");
           Date h = df.parse(jTable.getValueAt(Row, 5).toString());
           jDateChooser.setDate(h);
           btnAdd.setEnabled(false);
           btnDelete.setEnabled(true);
           btnClear.setEnabled(true);
       }
       catch(Exception ex){
       
         Tools.MsgBox("Erorr");
       }
    }//GEN-LAST:event_jTableMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    SetValues();
    Clear();
    a.getAllRow(jTable);

    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presenceOrAbsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presenceOrAbsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presenceOrAbsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presenceOrAbsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presenceOrAbsence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.button btnAdd;
    private Controls.button btnBack;
    private Controls.button btnClear;
    private Controls.button btnDelete;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtJop;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtSuper;
    // End of variables declaration//GEN-END:variables
}
